version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=***********
    env_file:
      - db.env
    networks:
      - Backend


  redis:
    image: redis
    restart: always
    networks:
      - Backend


  app:  
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - Backend


  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nextcloud"
      - "traefik.frontend.rule=Host:=***********"
    networks:
      - Backend
      - Frontend
      
 
  cron:
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - Backend



  traefik:
    build: ./reverse
    restart: always
    command: --api --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CLOUDFLARE_EMAIL=***********
      - CLOUDFLARE_API_KEY=***********
    ports:
     - "433:443"
     - "8080:8080"
    networks:
      - Frontend
      
 volumes:
  db:
  nextcloud:

  
networks:
  Backend:
  Frontend: